version: "3.9"
services:
  api:
    build: api
    ports:
      - 8080:8080
      - 9100:9100
      - 6060:6060
    command:
      - '-metrics-port=9100'
      - '-debug'
  frontend:
    build: frontend
    ports:
      - 3001:3001
    command:
      - npm
      - start
    environment:
      - PORT=3001
    volumes:
      - ./frontend/:/app
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./dev/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - api:api
  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ./dev/grafana/:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
  nginx:
    image: nginx:alpine
    volumes:
      - ./dev/nginx:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    links:
      - api

volumes:
  prometheus_data: {}
  grafana_data: {}