version: "3.9"
services:
  api:
    build: api
    ports:
      - 8080:8080
      - 9100:9100
      - 6060:6060
    command:
      - '-metrics-port=9100'
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./dev-prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - api:api

volumes:
  prometheus_data: {}