name: Build and Deploy

on:
  push:
    branches: [ main ]

concurrency: ci-${{ github.ref }}

env:
  assets-bucket: whobrokethecloud-assets

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
        working-directory: ${{ env.working-directory }}
      # - run: npm test
      #   working-directory: ${{ env.working-directory }}
      - run: npm run build
        env:
          CI: false
        working-directory: ${{ env.working-directory }}
      - name: Archive frontend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-assets
          path: |
            ${{ env.working-directory }}/build/
  publish-frontend:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
      - run: python -m pip install awscli s3cmd
      - name: Download frontend artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-assets
      - name: Upload frontend assets to object storage
        run: |
            s3cmd \
              --host=us-east-1.linodeobjects.com \
              --host-bucket="%(bucket)s.us-east-1.linodeobjects.com" \
              --no-mime-magic \
              --acl-public \
              sync \
              . \
              s3://${{ env.assets-bucket }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}