name: Build and Deploy

on:
  push: {}
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Archive frontend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-assets
          path: |
            build/
  publish:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
      - run: python -m pip install awscli
      - name: Download frontend artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-assets
      - run: ls