name: Load Test

on: workflow_dispatch

concurrency: loadtest-${{ github.ref }}

jobs:
  api:
    runs-on: ubuntu-latest
    name: Run JMeter Load Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
          unzip apache-jmeter-5.5.zip
      - name: Run JMeter Load test
        run: ./jmeter -n -t load_test.jmx -l data.csv -e -o dashboard/
      - uses: actions/upload-artifact@v3
        with:
          name: load-test-report
          path: dashboard/