name: Pull Request

on:
  # pull_request:
  #   branches:
  #     - '!main'
  #     - '!master'
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ${{ env.working-directory }}/package-lock.json
      - run: npm ci
        working-directory: ${{ env.working-directory }}
      - run: npm test
        working-directory: ${{ env.working-directory }}