name: Pull Request

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ]
    name: API - Go ${{ matrix.go }}
    env:
      working-directory: ./api
    steps:
      - uses: actions/checkout@v3
      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go test
  frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ${{ env.working-directory }}/package-lock.json
      - run: npm ci
        working-directory: ${{ env.working-directory }}
      - run: npm test
        working-directory: ${{ env.working-directory }}