name: Pull Request

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  api-image:
    runs-on: ubuntu-latest
    name: API - Docker Image
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: api/
          file: api/Dockerfile
          tags: whobrokethecloud/api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  api:
    runs-on: ubuntu-latest
    name: API - Go
    env:
      working-directory: ./api
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: ${{ env.working-directory }}/go.mod
          cache: true
          cache-dependency-path: ${{ env.working-directory }}/go.sum
      - name: Go test
        if: always()
        run: go test ./...
        working-directory: ${{ env.working-directory }}
      - name: Go vet
        if: always()
        run: go vet ./...
        working-directory: ${{ env.working-directory }}
      - name: Staticcheck
        if: always()
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.1"
          install-go: false
          cache-key: ${{ github.ref_name }}
          working-directory: ${{ env.working-directory }}
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18.x' ]
    name: Frontend - Node.JS ${{ matrix.node }}
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ${{ env.working-directory }}/package-lock.json
          node-version: ${{ matrix.node }}
      - run: npm ci
        working-directory: ${{ env.working-directory }}
      - run: npm test
        working-directory: ${{ env.working-directory }}