name: Pull Request

on:
  # pull_request:
  #   branches:
  #     - '!main'
  #     - '!master'
  push:
    branches:
      - '!main'
      - '!master'

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
        working-directory: ${{ env.working-directory }}
      - run: npm test
        working-directory: ${{ env.working-directory }}
      - run: npm run build
        env:
          CI: false
        working-directory: ${{ env.working-directory }}
      - name: Archive frontend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-assets
          path: |
            ${{ env.working-directory }}/build/